//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int id_dven { get; set; }
        public int id_ven { get; set; }
        public int id_art { get; set; }
        public int cantidad_dven { get; set; }
        public double precio_dven { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
